### ISSUE TITLE
rat

### ISSUE THREAD

**Issue by qualk** [h4xrOx/onetap_v4-crack#1]
i smell a rat

**Comment by h4xrOx** [comment]
Probably should take a shower if you smell like that.

**Comment by qualk** [comment]
damn, that's a good comeback.

But seriously, I smell a remote access trojan

**Comment by h4xrOx** [comment]
If you see an issue, fork this repo and create a pull request.
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
